name: Greetings

on:
  pull_request_target:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet the User
        run: |
          echo "Hello, ${{ github.actor }}! 👋 Thank you for creating your first issue or pull request in our repository. We appreciate your contribution!"
        shell: bash

      - name: Comment Greeting
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `Hello, @${{ github.actor }}! 👋 Thank you for creating your first issue or pull request in our repository. We appreciate your contribution!`;
            console.log(issueComment);
